#!/usr/bin/env bun
/**
 * Build lazygortex.
 *
 *   bun run scripts/build.ts            bundle + a binary for this machine
 *   bun run scripts/build.ts --bundle   just dist/cli.js (what npm ships)
 *   bun run scripts/build.ts --outfile dist/lazygortex-linux-x64   name the binary
 *
 * There is no cross-compilation: OpenTUI resolves its renderer from a native
 * module chosen per platform, and only the host's is installed, so release
 * binaries are built on a runner of each architecture.
 *
 * The Solid plugin has to run at build time: OpenTUI's Solid binding relies on
 * Solid's universal JSX transform, which Bun does not apply on its own. The
 * bundle is what the npm package ships, so an installed copy never depends on
 * this repo's bunfig.toml or tsconfig.json.
 */

import solidPlugin from "@opentui/solid/bun-plugin"
import { chmod } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import { join } from "node:path"

// fileURLToPath, not URL.pathname: a pathname is percent-encoded, so a checkout
// under `~/My Projects` would look for `.../My%20Projects/src` and fail with an
// error naming a directory that visibly does not exist
const root = fileURLToPath(new URL("..", import.meta.url))
const entrypoint = join(root, "src/index.tsx")

const args = process.argv.slice(2)
const bundleOnly = args.includes("--bundle")

/** `--outfile` with nothing after it used to build under the default name. */
function outfileArg(): string | undefined {
  const index = args.indexOf("--outfile")
  if (index === -1) return undefined
  const value = args[index + 1]
  if (!value || value.startsWith("-")) {
    console.error("build: --outfile needs a path")
    process.exit(2)
  }
  return value
}

const outfile = outfileArg()

function fail(result: { logs: unknown[] }): never {
  for (const log of result.logs) console.error(log)
  process.exit(1)
}

/**
 * The npm artefact: plain JS with a shebang, run by the user's own Bun.
 *
 * The runtime packages stay external — OpenTUI picks its native module per
 * platform through optional dependencies, which cannot be bundled — so the
 * published package installs them as normal dependencies.
 */
// Only the native core stays external: it picks a platform-specific optional
// dependency at runtime, which cannot be bundled. Solid and the Solid binding
// are bundled so an installed copy cannot resolve solid-js to its server build,
// which is what happens without this repo's bun configuration.
const RUNTIME_DEPS = ["@opentui/core"]

/**
 * Copyright notices for the code the bundle statically inlines.
 *
 * MIT requires its notice to travel with substantial portions of the software;
 * BSD-2-Clause requires binary redistribution to reproduce it. The list is read
 * back out of the bundle rather than written down here, so a dependency that
 * starts or stops being inlined cannot silently fall out of the file.
 */
async function writeNotices(bundle: string): Promise<void> {
  const packages = new Set<string>()
  for (const match of bundle.matchAll(/node_modules\/((?:@[^/\s"']+\/)?[^/\s"']+)\//g)) {
    packages.add(match[1]!)
  }
  // an empty set means the module banners no longer look the way this reads
  // them, not that the bundle suddenly inlines nothing
  if (packages.size === 0)
    throw new Error("no inlined dependencies found in the bundle — has the banner format changed?")

  const sections: string[] = []
  for (const name of [...packages].sort()) {
    const manifest = await Bun.file(join(root, "node_modules", name, "package.json")).json()
    const licence = await Bun.file(join(root, "node_modules", name, "LICENSE"))
      .text()
      .catch(() => "")
    if (!licence.trim()) throw new Error(`no LICENSE file for inlined dependency ${name}`)
    sections.push(
      [
        "-".repeat(72),
        `${name} ${manifest.version} (${manifest.license})`,
        "-".repeat(72),
        "",
        licence.trim(),
        "",
      ].join("\n"),
    )
  }

  const path = join(root, "THIRD-PARTY-NOTICES.txt")
  await Bun.write(
    path,
    [
      "lazygortex — third-party notices",
      "",
      "dist/cli.js statically inlines the packages below. This file is generated by",
      "scripts/build.ts from the licence text shipped with each of them; edit those,",
      "not this file.",
      "",
      ...sections,
    ].join("\n"),
  )
  console.log(`wrote ${path} for ${[...packages].sort().join(", ")}`)
}

async function buildBundle(): Promise<void> {
  const out = join(root, "dist/cli.js")
  const result = await Bun.build({
    entrypoints: [entrypoint],
    target: "bun",
    outdir: join(root, "dist"),
    naming: "cli.js",
    plugins: [solidPlugin],
    external: RUNTIME_DEPS,
    banner: "#!/usr/bin/env bun",
  })
  if (!result.success) fail(result)
  await chmod(out, 0o755)
  await writeNotices(await Bun.file(out).text())
  console.log(`built ${out}`)
}

/** A standalone executable with the Bun runtime embedded, for this platform. */
async function buildBinary(): Promise<void> {
  const out = outfile ?? join(root, "dist/lazygortex")
  const result = await Bun.build({
    entrypoints: [entrypoint],
    plugins: [solidPlugin],
    compile: { outfile: out },
  })
  if (!result.success) fail(result)
  console.log(`built ${out}`)
}

await buildBundle()
if (!bundleOnly) await buildBinary()
